### ISSUE TITLE
The following argument value is not valid: appName

### ISSUE THREAD

**Issue by sparty02** [orctom/was-maven-plugin#2]
An exception is thrown when attempting to deploy, regarding the 'appName' being invalid.  Using Java 7, Maven 3.2.5, WAS 8.5.5.

**Pom plugin config:**
- connectorType = SOAP

```
<plugin>
     <groupId>com.orctom.mojo</groupId>
     <artifactId>was-maven-plugin</artifactId>
     <version>1.0.7</version>
     <executions>
          <execution>
               <id>deploy</id>
               <phase>package</phase>
               <goals>
                    <goal>deploy</goal>
               </goals>
               <configuration>
                    <wasHome>${was.home}</wasHome>
                    <applicationName>${project.build.finalName}</applicationName>
                    <host>${deployment.server}</host>
                    <connectorType>${was.connector.type}</connectorType>
                    <port>${was.deploy.port}</port>
                    <user>${was.deploy.username}</user>
                    <password>${was.deploy.password}</password>
                    <server>${was.server}</server>
                    <node>${was.node}</node>
                    <virtualHost>${was.virtual.host}</virtualHost>
                    <contextRoot>${deploy.app.name}</contextRoot>
                    <verbose>true</verbose>
               </configuration>
          </execution>
     </executions>
</plugin>
```

**Py trace:**

```
[1/16/15 16:58:10:393 CST] 00000001 AbstractShell A   WASX7093I: Issuing message: "WASX7017E: Exception received while running file "**********\target\was-maven-plugin\py\deploy-*****[host]*****-*****[applicationName]*****.py"; exception information: com.ibm.bsf.BSFException: exception from Jython:
Traceback (innermost last):
  File "<string>", line 200, in ?
  File "<string>", line 180, in deploy
  File "<string>", line 177, in isApplicationInstalled
  File "*****[WAS_HOME]*****\scriptLibraries\application\V70\AdminApplication.py", line 4390, in checkIfAppExists
ScriptLibraryException: : 'exceptions.AttributeError WASL6041E: The following argument value is not valid: appName:.'
"
```

**Comment by orctom** [comment]
It should be the "applicationName" instead of "appName".
Can you please paste line 177 of that your python file here!

**Comment by sparty02** [comment]
Here are lines 176 and 177:

``` python
def isApplicationInstalled(self):
        return AdminApplication.checkIfAppExists(applicationName)
```

**Comment by sparty02** [comment]
Here's the whole python script if it's helpful:

``` python
import sys
import getopt
import time
import traceback

host = r""
cell = r""
cluster = r""
server = r""
node = r""
applicationName = r""
contextRoot = r""
virtualHost = r""
sharedLibs = r""
parentLast = r""
webModuleParentLast = r""
packageFile = r""

class WebSphere:
    def listApplications(self):
        print "[LIST APPLICATIONS]", host
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print AdminApp.list()

    def restartServer(self):
        print '-'*60
        print "[RESTARTING SERVER]", host
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60
        try:
            if "" != cluster:
                appManager = AdminControl.queryNames('name=' + cluster + ',type=Cluster,process=dmgr,*')
                print AdminControl.invoke(appManager, 'rippleStart')
                print ""
                print '='*60
                print "[NOTICE]: It takes a few minutes for the cluster to fully back running after the build finished!"
                print '='*60
                print ""
            else:
                appManager = AdminControl.queryNames('node=' + node + ',type=ApplicationManager,process=' + server + ',*')
                print AdminControl.invoke(appManager, 'restart')
        except:
            print "FAILED to restart cluster/server:"
            print '-'*10
            traceback.print_exc(file=sys.stdout)
            print '-'*10
            print "try to startApplication directly..."
            self.startApplication()

    def startApplication(self):
        print '-'*60
        print "[STARTING APPLICATION]", host, applicationName
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60
        try:
            if "" == node:
                appManager = AdminControl.queryNames('type=ApplicationManager,process=' + server + ',*')
            else:
                appManager = AdminControl.queryNames('node=' + node + ',type=ApplicationManager,process=' + server + ',*')
            print AdminControl.invoke(appManager, 'startApplication', applicationName)
            #AdminApplication.startApplicationOnCluster(applicationName, cluster)
        except:
            print "FAILED to start application:"
            print '-'*10
            traceback.print_exc(file=sys.stdout)
            print '-'*10

    def stopApplication(self):
        print '-'*60
        print "[STOPPING APPLICATION]", host, applicationName
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60
        try:
            if "" == node:
                appManager = AdminControl.queryNames('type=ApplicationManager,process=' + server + ',*')
            else:
                appManager = AdminControl.queryNames('node=' + node + ',type=ApplicationManager,process=' + server + ',*')
            print AdminControl.invoke(appManager, 'stopApplication', applicationName)
            #AdminApplication.stopApplicationOnCluster(applicationName, cluster)
        except:
            print "FAILED to stop application:"
            print '-'*10
            traceback.print_exc(file=sys.stdout)
            print '-'*10

    def installApplication(self):
        print '-'*60
        print "[INSTALLING APPLICATION]", host, applicationName
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60

        options = ['-deployws', '-distributeApp', '-appname', applicationName, '-server', server]

        try:
            if "" != cluster:
                serverMapping = 'WebSphere:cluster=' + cluster
                options += ['-cluster', cluster, '-MapModulesToServers', [['.*','.*', serverMapping]]]
            else:
                serverMapping = 'WebSphere:server=' + server
                options += ['-MapModulesToServers', [['.*','.*', serverMapping]]]

            if "" != contextRoot:
                options += ['-contextroot', contextRoot]

            if "" != virtualHost:
                options += ['-MapWebModToVH', [['.*','.*', virtualHost]]]

            if "" != sharedLibs:
                libs = []
                for lib in sharedLibs.split(','):
                    libs.append(['.*','.*', lib])
                options += ['-MapSharedLibForMod', libs]

            print ""
            print "options: ", options
            print ""

            print "INSTALLING"
            print AdminApp.install(packageFile, options)

            self.__modifyClassloader()

            print "SAVING CONFIG"
            AdminConfig.save()

            if "" != cluster:
                print "SYNCING"
                AdminNodeManagement.syncActiveNodes()

            result = AdminApp.isAppReady(applicationName)
            while result == "false":
                print "STATUS:", AdminApp.getDeployStatus(applicationName)
                time.sleep(5)
                result = AdminApp.isAppReady(applicationName)
            print "INSTALLED", applicationName
            return "true"
        except:
            print "FAILED to install application: ", applicationName
            print '-'*10
            traceback.print_exc(file=sys.stdout)
            print '-'*10
            return "false"

    def __modifyClassloader(self):
        deployments = AdminConfig.getid("/Deployment:" + applicationName + "/")
        deploymentObject = AdminConfig.showAttribute(deployments, "deployedObject")

        if "true" == parentLast:
            #AdminApplication.configureClassLoaderLoadingModeForAnApplication(applicationName, "PARENT_LAST")
            classloader = AdminConfig.showAttribute(deploymentObject, "classloader")
            AdminConfig.modify(classloader, [['mode', 'PARENT_LAST']])

        if "true" == webModuleParentLast:
            modules = AdminConfig.showAttribute(deploymentObject, "modules")
            arrayModules = modules[1:len(modules)-1].split(" ")
            for module in arrayModules:
                if module.find('WebModuleDeployment') != -1:
                    AdminConfig.modify(module, [['classloaderMode', 'PARENT_LAST']])

    def uninstallApplication(self):
        print '-'*60
        print "[UNINSTALLING APPLICATION]", host, applicationName
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60
        try:
            print AdminApp.uninstall(applicationName)
            AdminConfig.save()
            if "" != cluster:
                AdminNodeManagement.syncActiveNodes()
        except:
            print "FAILED to uninstall application: ", applicationName
            print '-'*10
            traceback.print_exc(file=sys.stdout)
            print '-'*10

    def isApplicationInstalled(self):
        return AdminApplication.checkIfAppExists(applicationName)

    def deploy(self):
        if "true" == self.isApplicationInstalled():
            self.uninstallApplication()

        if "true" == self.installApplication():
            self.restartServer()

        print '-'*60
        print "[FINISHED]", host, applicationName
        print time.strftime("%Y-%b-%d %H:%M:%S %Z")
        print '-'*60


#-----------------------------------------------------------------
# Main
#-----------------------------------------------------------------

if __name__ == "__main__":
    methods, args = getopt.getopt(sys.argv, 'o:')
    for name, method in methods:
        if name == "-o":
            getattr(WebSphere(), method)()
```

**Comment by orctom** [comment]
Please try the new version: 1.0.8.

**Comment by sparty02** [comment]
Looks like that solved the original issue I brought up!  However, now that it got to the point of installing the application, I hit an OutOfMemoryException (not enough heap space).  I'm not sure a simple MAVEN_OPTS="-Xmx1024m" (or whatever size is appropriate) will work because this plugin is, I'm assuming, spawning off additional processes to do it's Python stuff.  Thoughts?

This may be helpful:

```
Exception in thread "Bundle File Closer" java.lang.OutOfMemoryError: Java heap space
        at java.util.zip.ZipFile.close(Native Method)
        at java.util.zip.ZipFile.close(ZipFile.java:658)
        at org.eclipse.osgi.baseadaptor.bundlefile.ZipBundleFile.close(ZipBundleFile.java:313)
        at org.eclipse.osgi.baseadaptor.bundlefile.MRUBundleFileList.dispatchEvent(MRUBundleFileList.java:183)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:227)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:337)
FAILED to install application:  *****applicationName*****
----------
Traceback (most recent call last):
  File "<string>", line 119, in installApplication
com.ibm.ws.scripting.ScriptingException: com.ibm.ws.scripting.ScriptingException: com.ibm.websphere.management.application.client.AppDeploymentException: com.ibm.websphere.management.application.client.AppDeploymentException: java.lang.OutOfMemoryError: Java heap space [Root exception is java.lang.OutOfMemoryError: Java heap space]

java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space
```

**Comment by orctom** [comment]
Just updated this plugin to `1.0.9`, added an extra parameter `javaoption` to override it.

e.g.

``` xml
...
<configuration>
  ...
  <javaoption>-Xmx512m</javaoption>
  ...
</configuration>
...
```

or multiple args

``` xml
...
<configuration>
  ...
  <javaoption>-Xms512m -Xmx1024m</javaoption>
  ...
</configuration>
...
```

**Comment by sparty02** [comment]
That did it... thanks!
