### ISSUE TITLE
Can not deploy an ear project to WAS 8.5.5

### ISSUE THREAD

**Issue by nasrob** [orctom/was-maven-plugin#20]
Hello There,

I am trying to deploy an ear to a local WAS server, and I get this error :

```
[INFO] 
[INFO] --- was-maven-plugin:1.1.3.3:deploy (deploy) @ MyProjectEar ---
[INFO] was-maven-plugin - deploy
[INFO] Single target: localhost
[INFO] ============================================================
[INFO] [DEPLOY] localhost MyProjectEar-1.0.0-SNAPSHOT
[INFO] ============================================================
[INFO] ====================    pre-steps    =======================
[INFO] Skipped, not configured.
[INFO] ======================    deploy    ========================
wsadmin location: C:\PUBLIC\SOFTWARE2\bin\wsadmin.bat
Executing command:
cmd.exe /X /C "C:\PUBLIC\SOFTWARE2\bin\wsadmin.bat -conntype SOAP -host localhost -port 9082 -lang jython -tracefile 
C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\deploy-localhost-MyProjectEar-1.0.0-SNAPSHOT-20171130-152536-245.py.trace
 -appendtrace true -f C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\
 deploy-localhost-MyProjectEar-1.0.0-SNAPSHOT-20171130-152536-245.py -o deploy"
WASX7023E: Erreur lors de la cr‚ation de la connexion "SOAP" … l'h“te "localhost" ; informations sur l'exception : 
com.ibm.websphere.management.exception.ConnectorNotAvailableException: [SOAPException: faultCode=SOAP-ENV:Protocol; 
msg=Unsupported response content type &quot;text/html; charset=utf-8&quot;, must be: &quot;text/xml&quot;. Response was:
Error 404: com.ibm.ws.webcontainer.servlet.exception.NoTargetForURIException: No target servlet configured for uri: /
]
WASX7213I: Ce client de scriptage n'est pas connect‚ … un processus serveur ; consultez le fichier journal 
C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\deploy-localhost-MyProjectEar-1.0.0-SNAPSHOT-20171130-152536-245.py.trace
 pour plus d'informations.
WASX8011W: L'objet AdminTask n'est pas disponible.
WASX7303I: Les options suivantes sont transmises … l'environnement de scriptage et sont disponibles sous forme d'arguments 
stock‚s dans la variable argv : "[-o, deploy]"
---------------------------------------------------------------
 AdminApplication:       Check if application exists
 Application Name:       MyProjectEar-1.0.0-SNAPSHOT
 Usage: AdminApplication.checkIfAppExists("MyProjectEar-1.0.0-SNAPSHOT")
 Return: Checks whether the application exists. If the application exists, a true value is returned.
---------------------------------------------------------------
 
 
Exception: com.ibm.ws.scripting.ScriptingException com.ibm.ws.scripting.ScriptingException: 
WASX7070E: Le service de configuration n'est pas disponible. 
WASX7017E: Exception re‡ue lors de l'ex‚cution du fichier "C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\
deploy-localhost-MyProjectEar-1.0.0-SNAPSHOT-20171130-152536-245.py" ; informations sur l'exception : 
com.ibm.ws.scripting.ScriptingException: WASX7070E: Le service de configuration n'est pas disponible.

[ERROR] ##############  Exception occurred during deploying to WebSphere  ###############
[ERROR] com.orctom.was.model.WebSphereServiceException: Failed to deploy, return code: 105. Please make sure target WAS is alive and reachable.
	at com.orctom.was.service.impl.AbstractWebSphereServiceImpl.execute(AbstractWebSphereServiceImpl.java:68)
	at com.orctom.was.service.impl.AbstractWebSphereServiceImpl.deploy(AbstractWebSphereServiceImpl.java:60)
	at com.orctom.mojo.was.WASDeployMojo.execute(WASDeployMojo.java:81)
	at com.orctom.mojo.was.WASDeployMojo.execute(WASDeployMojo.java:67)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: com.orctom.was.model.WebSphereServiceException: Failed to deploy, return code: 105. Please make sure target WAS is alive and reachable.
	at com.orctom.mojo.was.WebSphereServiceImpl.executeCommand(WebSphereServiceImpl.java:53)
	at com.orctom.was.service.impl.AbstractWebSphereServiceImpl.execute(AbstractWebSphereServiceImpl.java:66)
	... 24 more
Caused by: com.orctom.was.model.WebSphereServiceException: Failed to deploy, return code: 105. Please make sure target WAS is alive and reachable.
	at com.orctom.mojo.was.WebSphereServiceImpl.executeCommand(WebSphereServiceImpl.java:67)
	at com.orctom.mojo.was.WebSphereServiceImpl.executeCommand(WebSphereServiceImpl.java:35)
	... 25 more

```

and my plugin configuration in the pom.xml is : 

```
<plugin>
			  <groupId>com.orctom.mojo</groupId>
			  <artifactId>was-maven-plugin</artifactId>
			  <version>1.1.3.3</version>
			  <executions>
			    <execution>
			      <id>deploy</id>
			      <phase>install</phase>
			      <goals>
			        <goal>deploy</goal>
			      </goals>
			    </execution>
			  </executions>
			  <configuration>
			    <wasHome>C:\PUBLIC\SOFTWARE2</wasHome>
			    <profileName>AppSrv01</profileName>
			    <conntype>SOAP</conntype>
			    <server>server1</server>
			    <node>FWPC-86733Node02</node>
			    <contextRoot>/PosteRiWebRef/</contextRoot>
			    <host>localhost</host>
			    <port>9082</port>
			    <verbose>true</verbose>
			    <!-- <updateExisting>false</updateExisting> -->
			  </configuration>
</plugin>


```
                         

Can you help me with this, Please?

**Comment by orctom** [comment]
The exception message is quite clear, you are run this against your local non-cluster WAS, you must make sure it's up and running, this plugin will talk to it to accomplish the deployment.
BTW, if I recall correctly, `port` is not the serving port, it should be the soap port

**Comment by nasrob** [comment]
Thank you for responding, I changed the port to the my SOAP port which is 8882, and now I get this error:

` com.ibm.ws.scripting.ScriptingException: com.ibm.ws.scripting.ScriptingException: WASX7109E: Insufficient Data for MapResRefToEJB Task `

and 

``` ADMA0007E: A validation error occurred in the Mapping resource references to resources task. The Java Naming and Directory Interface (JNDI) name is not specified for the mail / RiMailSession resource reference in the MyProject module with the EJB MailService name. ```

**Comment by orctom** [comment]
I guess there's some issue in the ear, or the ear is requesting something from WAS which is not correctly configured, try to generate the ear in maven, and have it installed into WAS manually,

**Comment by nasrob** [comment]
I did the reinstall of the ear with Log command assistance commands activated, which give me this command : 

```
 AdminApp.install('MyprojectEar.ear', '[  -nopreCompileJSPs -distributeApp -nouseMetaDataFromBinary -
deployejb -appname MyprojectEar -createMBeansForResources -noreloadEnabled -nodeployws -
validateinstallwarn -noprocessEmbeddedConfig -
filepermission.*\.dll=755#.*\.so=755#.*\.a=755#.*\.sl=755 -noallowDispatchRemoteInclude -
noallowServiceRemoteInclude -asyncRequestDispatchType DISABLED -nouseAutoLink -
noenableClientModule -clientMode isolated -novalidateSchema -MapResRefToEJB [[ MyprojectWeb MailService MyprojectWeb-1.0.0-SNAPSHOT.war, WEB-INF/ejb-jar.xml mail/RiMailSession javax.mail.Session jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb EmettService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb ImportDService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb MobiliteService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb VestParamService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb EAbementService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb DemandeService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb OperationService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb StatService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb StatbcService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]
[ MyprojectWeb ActionService MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/ejb-jar.xml jdbc/Mydatabase javax.sql.DataSource jdbc/Mydatabase "" "" "" ]] 
-MapModulesToServers [[ MyprojectWeb MyprojectWeb-1.0.0-SNAPSHOT.war,WEB-INF/web.xml WebSphere:cell=FWPC-86733Node02Cell,node=FWPC-86733Node02,server=server1 ]]]' ) ``` 

and it's complaining about MapResRefToEJB section.

**Comment by orctom** [comment]
You would need to add `<deployOptions>xxx</deployOptions>` to your config.
Such as `<deployOptions>-distributeApp -deployejb ...</deployOptions>.

And you might need to add `MapResRefToEJB` as well,

**Comment by nasrob** [comment]
Do I have to add them by using properties file or directly in the pom.xml?

**Comment by orctom** [comment]
either, if I recall it clearly

**Comment by nasrob** [comment]
I added `<deployOptions>-MapResRefToEJB -deployejb</deployOptions>` to the pom.xml and I got this error: 

```Traceback (most recent call last):
  File "<string>", line 137, in installApplication
com.ibm.ws.scripting.ScriptingException: com.ibm.ws.scripting.ScriptingException: java.lang.ClassCastException: java.lang.ClassCastException: java.lang.String incompatible with java.util.List```

**Comment by orctom** [comment]
There're a few log files in some where in target folder, can you attach them

**Comment by nasrob** [comment]
```************ Start Display Current Environment ************
Host Operating System is Windows 7, version 6.1
Java version = 1.6.0, Java Runtime Version = pwa6460_26sr8fp2ifx-20141114_01 (SR8 FP2), Java Compiler = j9jit26, Java VM name = IBM J9 VM
was.install.root = C:\PUBLIC\SOFTWARE2
user.install.root = C:\PUBLIC\SOFTWARE2\profiles\AppSrv01
Java Home = C:\PUBLIC\SOFTWARE2\java\jre
ws.ext.dirs = C:\\PUBLIC\\SOFTWARE2\\java\\lib;C:\\PUBLIC\\SOFTWARE2\\classes;C:\\PUBLIC\\SOFTWARE2\\lib;C:\\PUBLIC\\SOFTWARE2\\installedChannels;C:\\PUBLIC\\SOFTWARE2\\lib\\ext;C:\\PUBLIC\\SOFTWARE2\\web\\help;C:\\PUBLIC\\SOFTWARE2\\deploytool\\itp\\plugins\\com.ibm.etools.ejbdeploy\\runtime
Classpath = C:\PUBLIC\SOFTWARE2\profiles\AppSrv01\properties;C:\PUBLIC\SOFTWARE2\properties;C:\PUBLIC\SOFTWARE2\lib\startup.jar;C:\PUBLIC\SOFTWARE2\lib\bootstrap.jar;C:\PUBLIC\SOFTWARE2\java\lib\tools.jar;C:\PUBLIC\SOFTWARE2/lib/lmproxy.jar;C:\PUBLIC\SOFTWARE2/lib/urlprotocols.jar;C:\PUBLIC\SOFTWARE2\deploytool\itp\batchboot.jar;C:\PUBLIC\SOFTWARE2\deploytool\itp\batch2.jar
Java Library path = C:\PUBLIC\SOFTWARE2\java\jre\bin\compressedrefs;C:\PUBLIC\SOFTWARE2\java\jre\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\PUBLIC\SOFTWARE2\lib\native\win\x86_64;C:\PUBLIC\SOFTWARE2\bin;C:\PUBLIC\SOFTWARE2\java\bin;C:\PUBLIC\SOFTWARE2\java\jre\bin;C:\sybase\ADO.NET\dll;C:\sybase\OLEDB;C:\sybase\ODBC;C:\sybase\OCS-12_5\dll;C:\sybase\OCS-12_5\bin;C:\ProgramData\Oracle\Java\javapath;C:\sybase_12.5\ADO.NET\dll;C:\sybase_12.5\OLEDB;C:\sybase_12.5\ODBC;C:\sybase_12.5\OCS-12_5\dll;C:\sybase_12.5\OCS-12_5\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\IBM\SQLLIB\BIN;C:\Program Files\IBM\SQLLIB\FUNCTION;C:\Program Files\IBM\SQLLIB\SAMPLES\REPL;C:\APPLI\Ora10g\client_1\bin;C:\Program Files\Common Files\Hitachi ID\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files\Git\cmd;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Cloud Foundry;C:\Program Files\nodejs\;.
Orb Version = IBM Java ORB build orb626ifx-20140912.00 (IX90155)
Current trace specification = *=info
************* End Display Current Environment *************
[05/12/17 11:33:01:039 CET] 00000001 ManagerAdmin  I   TRAS0017I: L'état de démarrage de la trace est *=info.
[05/12/17 11:33:01:258 CET] 00000001 AbstractShell A   WASX7326I: Fichier de propriétés "/C:/PUBLIC/SOFTWARE2/profiles/AppSrv01/properties/wsadmin.properties" chargé.
[05/12/17 11:33:01:538 CET] 00000001 SSLConfig     W   CWPKI0041W: Un ou plusieurs magasins de clés utilisent le mot de passe par défaut.
[05/12/17 11:33:01:538 CET] 00000001 SSLConfigMana I   CWPKI0027I: Désactivation de la vérification du nom d'hôte par défaut pour les connexions d'URL HTTPS.
[05/12/17 11:33:01:694 CET] 00000001 AdminConfigCl A   WASX7208I: Paramètres de validation maintenant en vigueur : Niveau=HIGHEST, Validation  interdocuments=true, Fichier de sortie=C:/PUBLIC/SOFTWARE2/profiles/AppSrv01/logs/wsadmin.valout
[05/12/17 11:33:04:721 CET] 00000001 AbstractShell A   WASX7303I: Les options suivantes sont transmises à lenvironnement de scriptage et sont disponibles sous forme darguments stockés dans la variable argv : "[-o, deploy]"
[05/12/17 11:33:04:721 CET] 00000001 AbstractShell A   WASX7091I: Exécution du script : "C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\deploy-localhost-Mydatabase-1.0.0-SNAPSHOT-20171205-113259-136.py"
[05/12/17 11:33:07:217 CET] 00000001 wtp           W org.eclipse.jst.j2ee.commonarchivecore.internal.impl.WARFileImpl containsEJBContent IWAE0068W The EJB deployment descriptor META-INF/ejb-jar.xml in library archive PosteRiEjb-1.0.0-SNAPSHOT.jar is ignored. The product does not process deployment descriptor META-INF/ejb-jar.xml in library archives. Change the path of deployment descriptor META-INF/ejb-jar.xml to WEB-INF/ejb-jar.xml.
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-254972279 ( org.hibernate.annotations.JoinColumnOrFormula.formula ) ] Name [ null ] Description [ Lorg/hibernate/annotations/JoinFormula; ] Call in violation of protocol
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-223783214 ( org.hibernate.annotations.JoinColumnOrFormula.column ) ] Name [ null ] Description [ Ljavax/persistence/JoinColumn; ] Call in violation of protocol
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@651257029 ( org.hibernate.annotations.Table.foreignKey ) ] Name [ null ] Description [ Lorg/hibernate/annotations/ForeignKey; ] Call in violation of protocol
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-1797739099 ( org.hibernate.annotations.Table.sqlInsert ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLInsert; ] Call in violation of protocol
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-37394892 ( org.hibernate.annotations.Table.sqlUpdate ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLUpdate; ] Call in violation of protocol
[05/12/17 11:33:09:697 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@824958912 ( org.hibernate.annotations.Table.sqlDelete ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLDelete; ] Call in violation of protocol
[05/12/17 11:33:10:290 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@-1653009080 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-399845586 ( javax.servlet.annotation.ServletSecurity.value ) ] Name [ null ] Description [ Ljavax/servlet/annotation/HttpConstraint; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@1001275270 ( org.hibernate.annotations.JoinColumnOrFormula.formula ) ] Name [ null ] Description [ Lorg/hibernate/annotations/JoinFormula; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@153539540 ( org.hibernate.annotations.JoinColumnOrFormula.column ) ] Name [ null ] Description [ Ljavax/persistence/JoinColumn; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-576970511 ( org.hibernate.annotations.Table.foreignKey ) ] Name [ null ] Description [ Lorg/hibernate/annotations/ForeignKey; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-542742656 ( org.hibernate.annotations.Table.sqlInsert ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLInsert; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@121399456 ( org.hibernate.annotations.Table.sqlUpdate ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLUpdate; ] Call in violation of protocol
[05/12/17 11:33:11:117 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@2082860716 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@1596254291 ( org.hibernate.annotations.Table.sqlDelete ) ] Name [ null ] Description [ Lorg/hibernate/annotations/SQLDelete; ] Call in violation of protocol
[05/12/17 11:33:11:366 CET] 00000001 visitor       W com.ibm.ws.amm.scan.util.AnnotationInfoDefaultVisitor visitAnnotation [ com.ibm.ws.amm.scan.util.InfoVisitor@221607305 ] for method [ com.ibm.ws.amm.scan.util.info.impl.MethodInfoImpl@-1337556855 ( javax.servlet.annotation.ServletSecurity.value ) ] Name [ null ] Description [ Ljavax/servlet/annotation/HttpConstraint; ] Call in violation of protocol
[05/12/17 11:33:12:430 CET] 00000001 AbstractShell E   WASX7120E: Ci-après les informations de diagnostic de lexception dont le texte est "{0}" :

 {1}
[05/12/17 11:33:12:446 CET] 00000001 AbstractShell A   WASX7093I: Emission du message : "WASX7017E: Exception reçue lors de l'exécution du fichier "C:\PUBLIC\dev\workspace-rtc-6\MyProjectEar\target\was-maven-plugin\py\deploy-localhost-MyProjectEar-1.0.0-SNAPSHOT-20171205-113259-136.py" ; informations sur l'exception : java.lang.ClassCastException: java.lang.ClassCastException: java.lang.String incompatible with java.util.List
"
```
The local language is French.
