### ISSUE TITLE
Template 'jython\websphere.py' not found.

### ISSUE THREAD

**Issue by da-z** [orctom/was-maven-plugin#7]
Hi.

I'm getting the following error.

``` java
[ERROR] com.orctom.mojo.was.model.WebSphereServiceException: Template 'jython\websphere.py' not found
    at com.orctom.mojo.was.service.impl.WebSphereServiceScriptImpl.execute(WebSphereServiceScriptImpl.java:109)
    at com.orctom.mojo.was.service.impl.WebSphereServiceScriptImpl.deploy(WebSphereServiceScriptImpl.java:62)
    at com.orctom.mojo.was.WASDeployMojo.execute(WASDeployMojo.java:80)
    at com.orctom.mojo.was.WASDeployMojo.execute(WASDeployMojo.java:66)
```

**Comment by juantimonescalona** [comment]
You can use the default websphere.py
put the script in the same folder than the pom.xml

![image](https://cloud.githubusercontent.com/assets/6727333/9408137/102fc246-4810-11e5-8e5f-89a966efeb69.png)

**Comment by orctom** [comment]
da-z,

Your pom.xml please!

**Comment by da-z** [comment]
Tx Juan, that is what I eventually did. I was just expecting websphere.py to be picked up from the plugin's .jar, that's all.

@orctom, I don't have the pom.xml anymore, but it was the configured like in the example on the site, minus the `<script>` tag.
